#!/bin/bash
#
#==>  WAM post-processing pgrid
#
#     Arno Behrens (May 2019)
#
#SBATCH --job-name=pgrid
#SBATCH --partition=compute
#SBATCH --ntasks=1
#SBATCH --time=00:30:00
#SBATCH --mail-type=FAIL
#SBATCH --account=bu1213
#SBATCH --output=wam.o%j
#SBATCH --error=wam.e%j
#
module load intelmpi/2018.5.288 intel/18.0.4
#
set -k
WAMDIR=/pf/b/b381438/WAM
WORK=/work/bu1213/b381438/WAM
cd ${WORK}/tempsg
#
cp ${WAMDIR}/const/Coarse_Grid/JAN/Grid_User .
cp ${WAMDIR}/abs/pgrid pgrid.exe
#
./pgrid.exe
mv Grid_Prot ${WAMDIR}/dayfiles/pgrid_prot_coarse_JAN
rm Grid_User pgrid.exe
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PGRID.
# ===================================================================
#
