#!/bin/bash
#
#==>  WAM pre-processing preproc
#
#     Arno Behrens (May 2019)
#
#SBATCH --job-name=preproc
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:05:00
#SBATCH --mail-type=FAIL
#SBATCH --account=bu1213
#SBATCH --output=preproc.o%j
#SBATCH --error=preproc.e%j
#
module load intelmpi/2018.5.288 intel/18.0.4
#
set +k
WAMDIR=/pf/b/b381438/WAM
WORK=/work/bu1213/b381438/WAM
#
cd ${WORK}/tempsg
cp ${WAMDIR}/const/TOPOCAT.DAT .
cp ${WAMDIR}/const/Coarse_Grid/JAN/Preproc_User .
cp ${WAMDIR}/abs/preproc preproc.exe
#
srun ./preproc.exe
#
mv Preproc_Prot ${WAMDIR}/dayfiles/preproc_prot_coarse_JAN
mv Grid_info_COARSE_GRID ../work
rm Preproc_User preproc.exe TOPOCAT.DAT
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PREPROC.
# ===================================================================
#
