#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load intelmpi/2018.5.288 intel/18.0.4
    
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/ptime_S.mk $OBJDIR
cd $OBJDIR
make -f ptime_S.mk ptime_S
mv ptime_S $EXECDIR
rm -f ptime_S.mk
