#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load intelmpi/2018.5.288 intel/18.0.4
    
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/chief.mk $OBJDIR
cd $OBJDIR
make -f chief.mk chief
mv chief $EXECDIR/wam
rm -f chief.mk
