#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load intelmpi/2018.5.288 intel/18.0.4 

SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/pnetcdf.mk $OBJDIR
cd $OBJDIR
make -f pnetcdf.mk pnetcdf
mv pnetcdf $EXECDIR
rm -f pnetcdf.mk
