#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load intelmpi/2018.5.288 intel/18.0.4
    
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/ptime.mk $OBJDIR
cd $OBJDIR
make -f ptime.mk ptime
mv ptime $EXECDIR
rm -f ptime.mk
