#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load intelmpi/2018.5.288 intel/18.0.4

SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/pspec.mk $OBJDIR
cd $OBJDIR
make -f pspec.mk pspec
mv pspec $EXECDIR
rm -f pspec.mk
