#!/bin/sh
set -ex
. ${0%/*}/.dirset

module load intelmpi/2018.5.288 intel/18.0.4

SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/preproc.mk $OBJDIR
cd $OBJDIR
make -f preproc.mk preproc
mv preproc $EXECDIR
rm -f preproc.mk
