#!/bin/sh
set -ex
. ${0%/*}/.dirset
path_o=${PRODADMDIR}/obj
path_f=${PRODADMDIR}/src/print
    

module load intelmpi/2018.5.288 intel/18.0.4

modfile="wam_netcdf_module make_netcdf"

cd $path_o

for code in $modfile
do
   rm -f ${code}.f90 ${code}.o
   cp ${path_f}/${code}.f90 ${path_o}/${code}.f90
   mpiifort -c ${code}.f90 -I/sw/rhel6-x64/netcdf/netcdf_fortran-4.4.2-intel14/include
   rm -f ${code}.f90
done
